// Code generated by "stringer -type OdriveCommand godrive/odriveClientHandler.go"; DO NOT EDIT.

package godrive

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Authenticate-0]
	_ = x[Mount-1]
	_ = x[Unmount-2]
	_ = x[Backup-3]
	_ = x[Backupnow-4]
	_ = x[Removebackup-5]
	_ = x[Sync-6]
	_ = x[Placeholderthreshold-7]
	_ = x[Foldersyncrule-8]
	_ = x[Unsync-9]
	_ = x[Autounsyncthreshold-10]
	_ = x[Stream-11]
	_ = x[Refresh-12]
	_ = x[Xlthreshold-13]
	_ = x[Encpassphrase-14]
	_ = x[Syncstate-15]
	_ = x[Status-16]
	_ = x[Deauthorize-17]
	_ = x[Diagnostics-18]
	_ = x[Emptytrash-19]
	_ = x[Autotrashthreshold-20]
	_ = x[Restoretrash-21]
	_ = x[Shutdown-22]
}

const _OdriveCommand_name = "AuthenticateMountUnmountBackupBackupnowRemovebackupSyncPlaceholderthresholdFoldersyncruleUnsyncAutounsyncthresholdStreamRefreshXlthresholdEncpassphraseSyncstateStatusDeauthorizeDiagnosticsEmptytrashAutotrashthresholdRestoretrashShutdown"

var _OdriveCommand_index = [...]uint8{0, 12, 17, 24, 30, 39, 51, 55, 75, 89, 95, 114, 120, 127, 138, 151, 160, 166, 177, 188, 198, 216, 228, 236}

func (i OdriveCommand) String() string {
	if i < 0 || i >= OdriveCommand(len(_OdriveCommand_index)-1) {
		return "OdriveCommand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OdriveCommand_name[_OdriveCommand_index[i]:_OdriveCommand_index[i+1]]
}
