// Code generated by "stringer -type=placeholderSize -trimprefix=placeholderSize"; DO NOT EDIT.

package godrive

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[placeholderSizeNever-0]
	_ = x[placeholderSizeSmall-1]
	_ = x[placeholderSizeMedium-2]
	_ = x[placeholderSizeLarge-3]
	_ = x[placeholderSizeAlways-4]
}

const _placeholderSize_name = "NeverSmallMediumLargeAlways"

var _placeholderSize_index = [...]uint8{0, 5, 10, 16, 21, 27}

func (i placeholderSize) String() string {
	if i < 0 || i >= placeholderSize(len(_placeholderSize_index)-1) {
		return "placeholderSize(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _placeholderSize_name[_placeholderSize_index[i]:_placeholderSize_index[i+1]]
}
